name: Build Container

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.event.repository.name }}
        tags: latest ${{ steps.vars.outputs.tag }}
        containerfiles: |
          ./neovim.Dockerfile

    - name: Push To ghcr.io
      id: push-to-qhcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

  package-upload:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukegriffith/nvim-scripts:main
    needs: [ build ]
    steps:
      - name: Test NVIM
        run: nvim --headless -c "lua print(1)" -c "! whoami" -c "qa"
      - name: Package Config
        run: bash /root/package-config.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nvim-offline-deps.tar.gz
          path: nvim-offline-deps.tar.gz
