name: CI
on:
  push:
    branches: [ main ]
    #tags:
    #  - 'v*.*.*' 

jobs:
  package-upload:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukegriffith/nvim-scripts:main
    steps:
      - name: Test NVIM
        run: nvim --headless -c "lua print(1)" -c "qa"
      - name: Package Config
        run: bash /root/package-config.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nvim-offline-deps.tar.gz
          path: nvim-offline-deps.tar.gz
